<div id="subbar">
<div>
<a href="cesta.php"><?php if ($pagina_web=='cesta.php') { echo '<span class="negrita">'.$translate['mi_seleccion'].'</span>'; } else { echo $translate['mi_seleccion']; } ?></a>  |  
<a href="carpeta_trabajo.php"><?php if ($pagina_web=='carpeta_trabajo.php') { echo '<span class="negrita">'.$translate['gestionar_carpeta_trabajo'].'</span>'; } else { echo $translate['gestionar_carpeta_trabajo']; } ?></a>  |  
<a class="iframe" href="inc/herramientas/creador_animaciones.php"><?php if ($pagina_web=='inc/herramientas/creador_animaciones.php') { echo '<span class="negrita">'.$translate['creador_animaciones'].'</span>'; } else { echo $translate['creador_animaciones']; } ?></a> | 
<a class="iframe" href="inc/herramientas/creador_simbolos/creador_simbolos.php"><?php if ($pagina_web=='inc/herramientas/creador_simbolos/creador_simbolos.php') { echo '<span class="negrita">'.$translate['creador_de_simbolos'].'</span>'; } else { echo $translate['creador_de_simbolos']; } ?></a> | 
<a class="iframe" href="inc/herramientas/creador_frases/creador_frases.php"><?php if ($pagina_web=='inc/herramientas/creador_frases/creador_frases.php') { echo '<span class="negrita">'.$translate['creador_frases'].'</span>'; } else { echo $translate['creador_frases']; } ?></a> | <a class="iframe" href="inc/herramientas/generador_horarios/generador_horarios.php"><?php if ($pagina_web=='inc/herramientas/generador_horarios/generador_horarios.php') { echo '<span class="negrita">'.$translate['generador_horarios'].'</span>'; } else { echo $translate['generador_horarios']; } ?></a> | <a class="iframe" href="inc/herramientas/generador_calendarios/generador_calendarios.php"><?php if ($pagina_web=='inc/herramientas/generador_calendarios/generador_calendarios.php') { echo '<span class="negrita">'.$translate['generador_calendarios'].'</span>'; } else { echo $translate['generador_calendarios']; } ?></a> | <a class="iframe" href="inc/herramientas/generador_tableros/generador_tableros.php"><?php if ($pagina_web=='inc/herramientas/generador_tableros/generador_tableros.php') { echo '<span class="negrita">'.$translate['generador_tableros'].'</span>'; } else { echo $translate['generador_tableros']; } ?></a> | <a class="iframe" href="inc/herramientas/creador_bingos/creador_bingos.php"><?php if ($pagina_web=='inc/herramientas/creador_bingos/creador_bingos.php') { echo '<span class="negrita">'.$translate['creador_bingos'].'</span>'; } else { echo $translate['creador_bingos']; } ?></a>
 | <a class="iframe" href="inc/herramientas/creador_ocas/creador_ocas.php"><?php if ($pagina_web=='inc/herramientas/creador_ocas/creador_ocas.php') { echo '<span class="negrita">'.$translate['juego_oca'].'</span>'; } else { echo $translate['generador_dominos']; } ?></a> | <a class="iframe" href="inc/herramientas/generador_dominos/generador_dominos.php"><?php if ($pagina_web=='inc/herramientas/generador_dominos/generador_dominos.php') { echo '<span class="negrita">'.$translate['generador_dominos'].'</span>'; } else { echo $translate['generador_dominos']; } ?></a> | <a class="iframe" href="inc/herramientas/generador_encadenados/generador_dominos_encadenados.php"><?php if ($pagina_web=='inc/herramientas/generador_encadenados/generador_dominos_encadenados.php') { echo '<span class="negrita">'.$translate['generador_dominos_encadenados'].'</span>'; } else { echo $translate['generador_dominos_encadenados']; } ?></a>
</div>
</div>